

url: "https://davidaevans.github.io"
baseurl: "/"

sass:
  sass_dir: _sass
  style: compressed

author:
  name: "David Evans"
  bio: "PhD student at The University of Durham. Part of Cohort 7 of SOFI2 CDT."
  location: "Durham, UK"
  address1: "Address Line 1"
  address2: "Address Line 2"
  city: "Durham"
  postcode: "DH1 1DH"

socials:
  twitter: "davidevans120"
  instagram: "david_evans69"
  github: "davidaevans"
  email: "david.evans@dur.ac.uk"
  linkedin:

include:
  - _pages

exclude:
  - CNAME
  - design-pages


collections:
  blog:
    output: true
    permalink: /:collection/:path/
  diary:
    output: true
    permalink: /:collection/:path/
  #pages:
   # output: true
   # permalink: /:path/


kramdown:
# Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

version: v3.9.0